### ISSUE TITLE
When will more detailed usage steps be released?

### ISSUE THREAD

**Issue by deyang2000** [Traffic-X/MonoUNI#1]

**Comment by deyang2000** [comment]
In addition, I noticed another work called _Towards Scenario Generalization for Vision-based Roadside 3D Object Detection_ when looking up the data on roadside facility target detection. It solves the problem of background overfitting in homogeneous scenes through data augmentation and semi-supervised learning to improve the detection effect in heterogeneous scenes. Do you consider this in your work?

I would appreciate your quick feedback.

**Comment by jjrCN** [comment]
> In addition, I noticed another work called _Towards Scenario Generalization for Vision-based Roadside 3D Object Detection_ when looking up the data on roadside facility target detection. It solves the problem of background overfitting in homogeneous scenes through data augmentation and semi-supervised learning to improve the detection effect in heterogeneous scenes. Do you consider this in your work?
> 
> I would appreciate your quick feedback.

Thanks for your attention, we will release the training and inference code as soon as possible (probably this week or next week). 
Regarding SGV3D, it is the latest work in the BEVHeight series. You can directly consult their authors for discussion. Regarding solving the generalization problem of roadside 3D detection, we believe that the ambiguity of depth estimation introduced by focal length, and the difficulty of depth estimation caused by the diversity of pitch angles are two important factors, but heterogeneous and homologous sources of scenes are also important issues to be solve.

**Comment by deyang2000** [comment]
Nice job! Good luck with your work.
